on:
  push:
     branches:
       - main

name: render-presentation-en

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      SHINY_USERNAME: 'katherine-hebert'
      SHINY_TOKEN: ${{ secrets.TOKEN }}
      SHINY_SECRET: ${{ secrets.SECRET }}
      APP_NAME: 'myApp'
      APP_DIR: ''
        
    steps:
       - name: 🛎️ Checkout repository
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - id: deploy
    
       - name: 💎 Deploy to shinyapps.io
         uses: qwert666/shinyapps-actions@main